[windows]
dc01      ansible_host=10.10.0.10  ansible_password='wv)oO6uTQ2x*3lrgNt4$R7taJl1sFtZL'
off-wks01 ansible_host=10.10.20.10 ansible_password='cj7Z!zki!)Y!X7!=koF5xvqpv%Usn1Ld'
off-wks02 ansible_host=10.10.20.20 ansible_password='&ZtDkz%b&SOjTeJ7UI@kw*iH*dnvqJrW'
ca01      ansible_host=10.10.0.20  ansible_password='D*Ngl98O8=Hm1VO0xp@X=bH2Q!=TU9xf'
fs01      ansible_host=10.10.10.10 ansible_password='x=S;n)OCgUM3l?nFUl=b3==.avBwEIHK'
wef01     ansible_host=10.10.30.10 ansible_password='6@x4y.n$DtrSYW08wun8TEXaLJGknlNp'

[windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

[ubuntu]
off-wks03    ansible_host=10.10.20.30
ansible-temp ansible_host=10.10.40.10
elk01        ansible_host=10.10.30.20

[ubuntu:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=ssh_private_key.pem
ansible_python_interpreter=/usr/bin/python3
