- name: Normal activity - user

  debug:

    msg: "[NORMAL] User activity"


- name: Normal activity - admin

  debug:

    msg: "[NORMAL] Admin tasks"


- name: Normal activity - DNS

  debug:

    msg: "[NORMAL] DNS queries"
